name: Detect Secrets
on:
  workflow_call:

jobs:
  detect-secrets:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: docker://zricethezav/gitleaks:latest
        with:
          args: detect --redact --verbose
